/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 cub2.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/cub2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line001.geometry}
        material={materials["металл бак"]}
        position={[-0.185, -0.429, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line003.geometry}
        material={materials["металл бак"]}
        position={[-0.298, 0.131, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line004.geometry}
        material={materials["металл бак"]}
        position={[-0.148, 0.396, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line005.geometry}
        material={materials["металл бак"]}
        position={[-0.046, 0.154, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line006.geometry}
        material={materials["металл зеркало"]}
        position={[-0.327, -0.063, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube001.geometry}
        material={materials["металл бак"]}
        position={[-0.282, -0.176, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line007.geometry}
        material={materials["металл зеркало"]}
        position={[-0.327, 0.332, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line008.geometry}
        material={materials["металл бак"]}
        position={[-0.221, -0.078, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube007.geometry}
        material={materials["металл зеркало"]}
        position={[-0.009, -0.094, 0.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube008.geometry}
        material={materials.пластик}
        position={[-0.009, -0.08, 0.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube009.geometry}
        material={materials.пластик}
        position={[-0.017, -0.08, 0.064]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <group position={[-0.224, -0.327, 0.002]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line013.geometry}
          material={materials["металл зеркало"]}
          position={[0.019, -0.009, 0.089]}
          rotation={[Math.PI / 2, 0, -0.436]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle001.geometry}
          material={materials["металл зеркало"]}
          position={[0.214, -0.002, -0.002]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line014.geometry}
          material={materials["металл зеркало"]}
          position={[0.016, -0.009, -0.088]}
          rotation={[Math.PI / 2, 0, Math.PI / 9]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle003.geometry}
          material={materials["металл зеркало"]}
          position={[-0.043, -0.002, 0]}
        />
      </group>
      <group
        position={[0.206, -0.327, 0.002]}
        rotation={[0, 0, -Math.PI]}
        scale={[1, -1, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line015.geometry}
          material={materials["металл зеркало"]}
          position={[0.019, -0.009, 0.089]}
          rotation={[Math.PI / 2, 0, -0.436]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line016.geometry}
          material={materials["металл зеркало"]}
          position={[0.016, -0.009, -0.088]}
          rotation={[Math.PI / 2, 0, Math.PI / 9]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle004.geometry}
          material={materials["металл зеркало"]}
          position={[0.214, -0.002, -0.002]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle005.geometry}
          material={materials["металл зеркало"]}
          position={[-0.043, -0.002, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle006.geometry}
        material={materials["16 - Default"]}
        position={[-0.059, 0.148, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle007.geometry}
        material={materials.пластик}
        position={[-0.082, -0.149, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group position={[-0.009, -0.137, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["M56_X_55-17451||B8A4396250C5687B1D31E70758B30729E1AC4426"]
              .geometry
          }
          material={materials["металл зеркало"]}
          position={[-0.005, -0.015, 0.099]}
          rotation={[0, 1.57, 0]}
          scale={0.144}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus003.geometry}
          material={materials["металл зеркало"]}
          position={[-0.005, -0.004, 0.099]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.319}
        />
      </group>
      <group position={[-0.009, -0.137, 0]} rotation={[0, 1.257, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["M56_X_55-17451||B8A4396250C5687B1D31E70758B30729E1AC4427"]
              .geometry
          }
          material={materials["металл зеркало"]}
          position={[-0.005, -0.015, 0.099]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.144}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus004.geometry}
          material={materials["металл зеркало"]}
          position={[-0.005, -0.004, 0.099]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.319}
        />
      </group>
      <group
        position={[-0.009, -0.137, 0]}
        rotation={[-Math.PI, Math.PI / 5, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["M56_X_55-17451||B8A4396250C5687B1D31E70758B30729E1AC4428"]
              .geometry
          }
          material={materials["металл зеркало"]}
          position={[-0.005, -0.015, 0.099]}
          rotation={[0, 1.57, 0]}
          scale={0.144}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus005.geometry}
          material={materials["металл зеркало"]}
          position={[-0.005, -0.004, 0.099]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.319}
        />
      </group>
      <group
        position={[-0.009, -0.137, 0]}
        rotation={[Math.PI, -Math.PI / 5, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["M56_X_55-17451||B8A4396250C5687B1D31E70758B30729E1AC4429"]
              .geometry
          }
          material={materials["металл зеркало"]}
          position={[-0.005, -0.015, 0.099]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.144}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus006.geometry}
          material={materials["металл зеркало"]}
          position={[-0.005, -0.004, 0.099]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.319}
        />
      </group>
      <group position={[-0.009, -0.137, 0]} rotation={[0, -1.257, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["M56_X_55-17451||B8A4396250C5687B1D31E70758B30729E1AC4430"]
              .geometry
          }
          material={materials["металл зеркало"]}
          position={[-0.005, -0.015, 0.099]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.144}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus007.geometry}
          material={materials["металл зеркало"]}
          position={[-0.005, -0.004, 0.099]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.319}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line009.geometry}
        material={materials.пластик}
        position={[-0.136, 0.566, 0.111]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube005.geometry}
        material={materials.пластик}
        position={[-0.158, 0.565, 0.106]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube004.geometry}
        material={materials.пластик}
        position={[-0.15, 0.565, 0.107]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube003.geometry}
        material={materials["металл зеркало"]}
        position={[-0.15, 0.565, 0.093]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tube002.geometry}
        material={materials["металл бак"]}
        position={[-0.15, 0.565, 0.054]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle008.geometry}
        material={materials["металл зеркало"]}
        position={[-0.08, 0.149, 0.035]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DIN912_M5x30mm_Partial.geometry}
        material={materials["металл зеркало"]}
        position={[-0.08, 0.149, 0.016]}
        rotation={[-Math.PI, 0, 0]}
        scale={1.677}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus001.geometry}
        material={materials["металл зеркало"]}
        position={[-0.08, 0.149, -0.008]}
        rotation={[0, -1.57, 0]}
        scale={[1, 2.891, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object002.geometry}
        material={materials["металл бак"]}
        position={[-0.01, 0.141, 0]}
        rotation={[0, -1.57, 0]}
        scale={1.258}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials["металл бак"]}
        position={[-0.01, 0.141, 0]}
        rotation={[0, -1.57, 0]}
        scale={1.258}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Capsule002.geometry}
        material={materials["металл зеркало"]}
        position={[0.052, 0.139, 0]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Capsule001.geometry}
        material={materials["металл зеркало"]}
        position={[-0.08, 0.139, -0.008]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl002.geometry}
        material={materials["17 - Default"]}
        position={[-0.179, 0.566, 0.157]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl001.geometry}
        material={materials["17 - Default"]}
        position={[-0.121, 0.566, 0.157]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group
        position={[-0.151, 0.563, 0.118]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.126, 1.126, 0.771]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NGon001_1.geometry}
          material={materials["Material #76"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NGon001_2.geometry}
          material={materials.пластик}
        />
      </group>
      <group position={[-0.008, -0.08, 0.064]} rotation={[-0.262, 0, 0]}>
        <group position={[0, 0, 0.037]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl003.geometry}
            material={materials["17 - Default"]}
            position={[0.029, 0.001, 0.016]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl004.geometry}
            material={materials["17 - Default"]}
            position={[-0.029, 0.001, 0.016]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <group
            position={[-0.001, -0.002, -0.023]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.126, 1.126, 0.771]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.NGon002_1.geometry}
              material={materials["Material #76"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.NGon002_2.geometry}
              material={materials.пластик}
            />
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line012.geometry}
          material={materials.пластик}
          position={[0.014, 0, 0.005]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
      </group>
      <group position={[-0.01, -0.005, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials["металл зеркало"]}
          position={[0, -0.142, 0]}
          rotation={[-Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials["металл зеркало"]}
          position={[0, 0.147, 0]}
          rotation={[-Math.PI, 0, 0]}
        />
        <group position={[0, 0.004, 0]}>
          <group position={[0, -0.118, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle018.geometry}
              material={materials["металл зеркало"]}
              position={[0.019, 0, -0.01]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle019.geometry}
              material={materials["металл зеркало"]}
              position={[0.002, 0, 0.026]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle020.geometry}
              material={materials["металл зеркало"]}
              position={[0.002, 0, -0.025]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002.geometry}
              material={materials["металл зеркало"]}
              position={[0, -0.002, 0]}
              rotation={[-Math.PI, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle021.geometry}
              material={materials["металл зеркало"]}
              position={[-0.017, 0, 0.013]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle022.geometry}
              material={materials["металл зеркало"]}
              position={[-0.017, 0, -0.01]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle017.geometry}
              material={materials["металл зеркало"]}
              position={[0.019, 0, 0.013]}
              rotation={[-Math.PI, 0, -0.262]}
            />
          </group>
          <group position={[0, -0.039, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder003.geometry}
              material={materials["металл зеркало"]}
              position={[0, -0.002, 0]}
              rotation={[-Math.PI, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle023.geometry}
              material={materials["металл зеркало"]}
              position={[0.019, 0, 0.013]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle024.geometry}
              material={materials["металл зеркало"]}
              position={[0.019, 0, -0.01]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle025.geometry}
              material={materials["металл зеркало"]}
              position={[0.002, 0, 0.026]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle026.geometry}
              material={materials["металл зеркало"]}
              position={[0.002, 0, -0.025]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle027.geometry}
              material={materials["металл зеркало"]}
              position={[-0.017, 0, 0.013]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle028.geometry}
              material={materials["металл зеркало"]}
              position={[-0.017, 0, -0.01]}
              rotation={[-Math.PI, 0, -0.262]}
            />
          </group>
          <group position={[0, 0.039, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004.geometry}
              material={materials["металл зеркало"]}
              position={[0, -0.002, 0]}
              rotation={[-Math.PI, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle029.geometry}
              material={materials["металл зеркало"]}
              position={[0.019, 0, 0.013]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle030.geometry}
              material={materials["металл зеркало"]}
              position={[0.019, 0, -0.01]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle031.geometry}
              material={materials["металл зеркало"]}
              position={[0.002, 0, 0.026]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle032.geometry}
              material={materials["металл зеркало"]}
              position={[0.002, 0, -0.025]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle033.geometry}
              material={materials["металл зеркало"]}
              position={[-0.017, 0, 0.013]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle034.geometry}
              material={materials["металл зеркало"]}
              position={[-0.017, 0, -0.01]}
              rotation={[-Math.PI, 0, -0.262]}
            />
          </group>
          <group position={[0, 0.118, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials["металл зеркало"]}
              position={[0, -0.002, 0]}
              rotation={[-Math.PI, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle035.geometry}
              material={materials["металл зеркало"]}
              position={[0.019, 0, 0.013]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle036.geometry}
              material={materials["металл зеркало"]}
              position={[0.019, 0, -0.01]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle037.geometry}
              material={materials["металл зеркало"]}
              position={[0.002, 0, 0.026]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle038.geometry}
              material={materials["металл зеркало"]}
              position={[0.002, 0, -0.025]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle039.geometry}
              material={materials["металл зеркало"]}
              position={[-0.017, 0, 0.013]}
              rotation={[-Math.PI, 0, -0.262]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle040.geometry}
              material={materials["металл зеркало"]}
              position={[-0.017, 0, -0.01]}
              rotation={[-Math.PI, 0, -0.262]}
            />
          </group>
        </group>
      </group>
      <group position={[-0.01, -0.001, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box001.geometry}
          material={materials["металл бак"]}
          position={[0, -0.147, 0]}
          rotation={[-Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line002.geometry}
          material={materials["металл бак"]}
          position={[-0.058, -0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cub2.glb");
